export const saveLibraryModalStyles = `
  .modal.modal-wide{width:min(1100px,96vw);max-height:92dvh;border-radius:18px;background:#10151b;overflow:hidden}
  .modal::before,.title,.btns{display:none}.body{padding:0;color:inherit}
  @media(max-width:600px){.overlay{padding:8px}.modal.modal-wide{width:100%;max-height:96dvh;border-radius:14px}.body{padding:0}}
`;

export const saveLibraryStyles = `
  :host{display:block;color:#e8e4d9;font:14px/1.6 'Noto Sans SC','Microsoft YaHei UI',system-ui,sans-serif;--line:#e8e4d916;--muted:#999fA7;--accent:#ef805c}
  *{box-sizing:border-box}button,input,select,textarea{font:inherit;color:inherit}button{cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}button:focus-visible,summary:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid #efa46b;outline-offset:3px}button,select,input{transition:background .15s,border-color .15s}
  svg{vertical-align:middle;flex-shrink:0}.library{display:flex;flex-direction:column;max-height:92dvh;min-height:min(570px,92dvh);overflow:hidden;background:radial-gradient(ellipse at 98% 0, #7c574321,transparent 45%)}
  .header{display:flex;align-items:center;gap:15px;padding:26px 30px 22px}.seal{display:grid;place-items:center;width:48px;height:52px;border:1px solid #db9e6252;border-radius:9px;color:#e1bb8c;background:#d39a6510;box-shadow:0 0 0 4px #d39a6505}
  .eyebrow{color:#cba67f;font-size:10px;letter-spacing:3px;font-weight:600}.header h2{font:600 25px/1.4 'Noto Serif SC','Songti SC',serif;letter-spacing:2px;margin:2px 0 0}.header p{margin:3px 0 0;font-size:12px;color:var(--muted)}.close{margin-left:auto;align-self:flex-start}
  .icon-button{border:1px solid transparent;background:transparent;color:#aab0b6;width:34px;height:34px;border-radius:8px;display:inline-flex;align-items:center;justify-content:center}.icon-button:hover{background:#ffffff0a;border-color:var(--line);color:#fff}.danger:hover{color:#ff9797;background:#ff777711}
  .tabs{display:flex;gap:8px;margin:0 30px;border-bottom:1px solid var(--line)}.tabs button{display:flex;align-items:center;justify-content:center;gap:9px;border:0;border-bottom:2px solid transparent;background:transparent;padding:13px 16px;color:var(--muted);margin-bottom:-1px;font-size:13px;font-weight:600}.tabs button[aria-selected=true]{border-bottom-color:var(--accent);color:#ffc2a5;background:linear-gradient(0deg,#f0816010,transparent)}.count{font:10px/1.5 system-ui;background:#ffffff0b;border-radius:5px;padding:1px 5px;color:#b6bac0}
  .workspace{overflow:auto;overscroll-behavior:contain;padding:22px 30px 28px;flex:1;min-height:0;scrollbar-width:thin;scrollbar-color:#77808b55 transparent}.current{display:flex;align-items:center;gap:16px;border:1px solid #c5976330;background:linear-gradient(110deg,#8e684d1a,#ffffff03);padding:18px 20px;border-radius:12px;margin-bottom:20px}.current-badge{width:45px;height:45px;display:grid;place-items:center;border:1px solid #d2a67135;border-radius:50%;color:#edc190;font:21px 'Noto Serif SC',serif;background:#bb845916}.current-info{min-width:0;flex:1}.overline{display:flex;align-items:center;gap:6px;color:#d6b28a;font-size:10px;letter-spacing:1px}.live-dot{width:5px;height:5px;border-radius:50%;background:#b4ccaa}.current h3{font-size:17px;margin:2px 0;overflow-wrap:anywhere}.current p{font-size:12px;color:var(--muted);margin:0}.current-actions{display:flex;gap:8px;flex-wrap:wrap}
  .button{display:inline-flex;align-items:center;justify-content:center;gap:7px;background:#ffffff06;border:1px solid #ffffff17;padding:8px 12px;border-radius:8px;white-space:nowrap;font-size:12px;min-height:36px}.button:hover{background:#ffffff0d;border-color:#ffffff30}.button.primary{color:#fff4ec;background:#b75839;border-color:#df7653;box-shadow:0 4px 14px #0002}.button.primary:hover{background:#ce6441}.button.quiet{color:#c0c5ca;background:transparent}.button.small{padding:6px 11px;min-height:32px}
  .toolbar{display:flex;align-items:center;gap:10px;margin:0 0 16px;flex-wrap:wrap}.search{display:flex;align-items:center;gap:8px;flex:1;min-width:170px;background:#070c1280;border:1px solid var(--line);border-radius:8px;padding:0 11px;color:#828b97}.search input{width:100%;min-width:0;border:0;background:none;outline:none;padding:9px 0;font-size:12px}.toolbar select{background:#151b22;border:1px solid var(--line);border-radius:8px;padding:8px 10px;font-size:12px}.hint{color:var(--muted);font-size:12px;margin:0 0 14px;line-height:1.7}.status{background:#192f2c;border:1px solid #4e9d8860;color:#b9e0d4;border-radius:8px;padding:9px 12px;font-size:12px;margin:0 0 14px;white-space:pre-wrap;overflow-wrap:anywhere}.status[data-error=true]{background:#321e20;color:#ffb3ad;border-color:#bf6c6450}.status:empty{display:none}
  .list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.entry{position:relative;min-width:0;border:1px solid var(--line);border-radius:12px;background:linear-gradient(150deg,#ffffff05,#ffffff01);padding:18px;display:flex;flex-direction:column;gap:11px;transition:border-color .2s,background .2s}.entry:hover{border-color:#e8e4d930;background:#ffffff04}.entry:before{content:'';position:absolute;top:18px;left:0;height:25px;width:2px;background:var(--entry-color,#d79267);border-radius:2px}.entry-head{display:flex;align-items:flex-start;gap:10px}.entry h3{margin:0;font-size:15px;font-weight:600;line-height:1.55;overflow-wrap:anywhere;flex:1}.tag{display:inline-flex;align-items:center;gap:4px;border:1px solid #ffffff14;border-radius:5px;padding:2px 6px;white-space:nowrap;font-size:10px;color:#a9afb8;background:#ffffff03}.tag.active{color:#acd6c1;border-color:#699f8450;background:#699f8412}.tag.if{color:#bdc5f6;border-color:#7788c947;background:#7788c912}.metadata{display:flex;align-items:center;gap:12px;flex-wrap:wrap;color:#aaaeb5;font-size:11px}.metadata span{display:flex;align-items:center;gap:5px}.excerpt{font-size:12px;line-height:1.75;color:#8e959f;margin:0;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;overflow-wrap:anywhere;min-height:40px}.entry-footer{display:flex;align-items:center;gap:8px;justify-content:space-between;padding-top:12px;border-top:1px solid var(--line);margin-top:auto}.entry-ops{display:flex;gap:2px;align-items:center}.entry-time{font-size:10px;color:#777f89;margin:0}.branch-route{font-size:11px;color:#a0a9ba;display:flex;gap:8px;align-items:center;background:#8398ce0b;border:1px solid #8398ce15;border-radius:7px;padding:8px 10px}.branch-route span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.entry-actions{display:flex;gap:6px;flex-wrap:wrap}.entry.current-line{border-color:#7b9f8650;background:#7b9f8607}
  .empty{grid-column:1/-1;display:flex;align-items:center;justify-content:center;flex-direction:column;text-align:center;border:1px dashed #e8e4d91c;border-radius:12px;padding:38px 24px;min-height:230px;background:radial-gradient(ellipse at 50% 40%,#c18b6410,transparent 70%)}.empty-mark{color:#c29e77;background:#b2865d0a;border:1px solid #b2865d2b;width:64px;height:70px;border-radius:12px;display:grid;place-items:center;margin-bottom:17px}.empty h3{font:500 18px 'Noto Serif SC',serif;letter-spacing:1px;margin:0 0 8px}.empty p{max-width:420px;color:#929aa4;font-size:12px;line-height:1.8;margin:0}.empty .button{margin-top:18px}
  .footer{display:flex;justify-content:space-between;gap:12px;padding:13px 30px;border-top:1px solid var(--line);background:#070c1255;font-size:10px;color:#808995}.footer span{display:flex;align-items:center;gap:6px}.preview{margin-top:20px;border:1px solid var(--line);border-radius:12px;padding:18px;background:#070c1244}.preview-heading{display:flex;align-items:center;justify-content:space-between;gap:10px}.preview h3,.preview h4{margin:0;font-size:14px}.preview h4{margin-top:18px;font-size:12px;color:#c5ae93}.preview pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.9 system-ui;color:#c8c6bf;max-height:360px;overflow:auto;margin:10px 0}.preview summary{cursor:pointer;font-size:12px;color:#aab0ba;margin-top:14px}.icon-button svg,.button svg,.tabs svg,.footer svg{pointer-events:none}[hidden]{display:none!important}
  @media(max-width:760px){.current{align-items:flex-start;flex-wrap:wrap}.current-actions{width:100%;padding-left:61px}.list{grid-template-columns:1fr}.header{padding:20px 20px 16px}.tabs{margin:0 20px}.workspace{padding:18px 20px 22px}.footer{padding:12px 20px}}
  @media(max-width:500px){.library{min-height:min(680px,94dvh);max-height:94dvh}.header{padding:17px 16px 14px;gap:11px}.seal{width:39px;height:44px}.header h2{font-size:22px}.header p{font-size:11px}.eyebrow{font-size:9px;letter-spacing:2px}.tabs{margin:0 14px;gap:0}.tabs button{flex:1;font-size:12px;padding:12px 5px;gap:5px}.tabs svg{width:15px}.workspace{padding:16px 14px 20px}.current{padding:15px;gap:11px}.current-actions{padding:0}.current-actions .button{flex:1}.current-badge{width:39px;height:39px}.current h3{font-size:15px}.toolbar{gap:7px}.search{flex-basis:100%;order:-1}.toolbar .button{padding:7px 9px}.toolbar select{flex:1;min-width:0}.entry{padding:15px}.entry-ops .icon-button{width:32px;height:34px}.footer{padding:11px 15px;flex-wrap:wrap;gap:4px}.footer span:last-child{font-size:9px}.empty{min-height:220px;padding:30px 18px}}
  @media(prefers-reduced-motion:reduce){*{transition:none!important;animation:none!important}}
`;
